[project]
name = "gruppe2-lagerassistent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai",
    "python-dotenv",
    "gradio",
    "openai-agents",
]
